# Generated by Django 3.0.5 on 2021-08-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_auto_20210805_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
