# Generated by Django 3.0.5 on 2021-07-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(blank=True, verbose_name='Подписан ли текущий пользователь на этого'),
        ),
    ]
